modLoader="javafml" 
loaderVersion="[36,)" 
license="MIT"
[[mods]] 
modId="elementalfoxes" 
version="${file.jarVersion}" 
displayName="Elemental Foxes" 
logoFile="examplemod.png" 
credits="Tutorial by Cy4, created by Harlefox" 
description='''
Mod by Harlefox.

Elemental foxes 
TBD
'''
[[dependencies.elementalfoxes]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.elementalfoxes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
